import { useQuery } from '@tanstack/react-query'
import { getAbBenchmarkStatus } from '../api/evaluation'
import { queryKeys } from '../api/queryKeys'
import type { ABPipelineRun } from '../api/types'
import { RunResultsTable } from '../components/evaluation/RunResultsTable'
import { ErrorBanner } from '../components/shared/ErrorBanner'
import { LoadingSkeleton } from '../components/shared/LoadingSkeleton'
import { StatTile } from '../components/shared/StatTile'

function pct(x: number | null): string {
  return x !== null ? `${Math.round(100 * x)}%` : '—'
}

function pctRatio(correct: number, total: number): string {
  return total > 0 ? `${Math.round((100 * correct) / total)}%` : '—'
}

function PipelineRunColumn({ title, run }: { title: string; run: ABPipelineRun }) {
  const s = run.summary
  return (
    <div>
      <h2 className="mb-2 text-sm font-semibold text-neutral-100">{title}</h2>
      <div className="mb-3 grid grid-cols-2 gap-2">
        <StatTile
          label="Clear-case accuracy"
          value={pctRatio(s.clear_correct, s.clear_total)}
          sublabel={`${s.clear_correct}/${s.clear_total}`}
        />
        <StatTile
          label="Recall@3"
          value={pctRatio(s.recall3_correct, s.recall3_total)}
          sublabel={`${s.recall3_correct}/${s.recall3_total}`}
        />
      </div>
      <RunResultsTable results={run.results} />
    </div>
  )
}

export function ABBenchmarkPage() {
  const { data, isLoading, isError, error, refetch } = useQuery({
    queryKey: queryKeys.abBenchmarkStatus,
    queryFn: ({ signal }) => getAbBenchmarkStatus(signal),
  })

  const cmp = data?.comparison

  return (
    <div>
      <h1 className="mb-1 text-lg font-semibold text-neutral-100">Reranker A/B Benchmark</h1>
      <p className="mb-4 text-xs text-neutral-500">
        Full benchmark suite run through both the original pipeline (with cross-encoder) and the
        experimental pipeline (without it), scored against{' '}
        <code className="text-neutral-400">data/sample_dataset/eval_queries.py</code>. Generated by{' '}
        <code className="text-neutral-400">scripts/run_ab_benchmark.py</code>, which warms up both
        pipelines first and alternates which one runs first per query to avoid cache/order bias.
      </p>

      {isLoading && <LoadingSkeleton shape="tile" count={4} />}
      {isError && <ErrorBanner error={error} onRetry={() => refetch()} />}

      {data && !data.with_reranker && (
        <div className="rounded-lg border border-dashed border-neutral-800 p-6 text-center text-sm text-neutral-500">
          {data.message}
        </div>
      )}

      {data?.with_reranker && data.no_reranker && cmp && (
        <div className="space-y-6">
          <div>
            <div className="mb-2 flex items-baseline justify-between">
              <h2 className="text-sm font-semibold text-neutral-300">Comparison summary</h2>
              <span className="text-xs text-neutral-500">
                {data.generated_at ?? data.source_file} &middot; {data.source_file}
                {data.warmup_performed === false && ' · WARNING: run without warm-up'}
              </span>
            </div>
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
              <StatTile
                label="Clear accuracy (with / without)"
                value={`${pct(cmp.clear_accuracy_with_reranker)} / ${pct(cmp.clear_accuracy_no_reranker)}`}
              />
              <StatTile
                label="Recall@3 (with / without)"
                value={`${pct(cmp.recall3_with_reranker)} / ${pct(cmp.recall3_no_reranker)}`}
              />
              <StatTile
                label="Ticket selection changed"
                value={`${cmp.ticket_selection_changed_count}/${cmp.n_queries}`}
                status={cmp.ticket_selection_changed_count > 0 ? 'warn' : 'ok'}
              />
              <StatTile label="Avg cross-encoder time" value={`${cmp.avg_cross_encoder_ms.toFixed(0)} ms`} />
              <StatTile
                label="Avg total time (with / without)"
                value={`${cmp.avg_total_time_s_with_reranker.toFixed(1)}s / ${cmp.avg_total_time_s_no_reranker.toFixed(1)}s`}
              />
              <StatTile
                label="Validation checks passed"
                value={`${cmp.validation_pass_count}/${cmp.validation_total}`}
                status={cmp.validation_pass_count === cmp.validation_total ? 'ok' : 'warn'}
              />
            </div>
            {cmp.ticket_selection_changed_keys.length > 0 && (
              <p className="mt-2 text-xs text-neutral-500">
                Changed queries: {cmp.ticket_selection_changed_keys.join(', ')}
              </p>
            )}
            {cmp.validation_failures.length > 0 && (
              <div className="mt-2 rounded border border-amber-800 bg-amber-950/40 p-2 text-xs text-amber-300">
                {cmp.validation_failures.length} quer{cmp.validation_failures.length === 1 ? 'y' : 'ies'}{' '}
                failed the automated pre-flight checks -- see the raw benchmark JSON for details.
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
            <PipelineRunColumn title="Original Pipeline (With Cross-Encoder)" run={data.with_reranker} />
            <PipelineRunColumn title="Experimental Pipeline (Without Cross-Encoder)" run={data.no_reranker} />
          </div>
        </div>
      )}
    </div>
  )
}
