"""initial schema

Revision ID: 817ec074e0f5
Revises: 
Create Date: 2026-07-23 01:06:00.214273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '817ec074e0f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_index(op.f('ix_customer_emails_customer_id'), 'customer_emails', ['customer_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CLAIM_DENIAL', 'PRIOR_AUTH', 'PAYMENT_POSTING', 'DOCUMENTATION_REQUEST', 'INSURANCE_VERIFICATION', 'NEW_SERVICE_REQUEST', 'GENERAL_ENQUIRY', name='ticketcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_index('ix_tickets_customer_status', 'tickets', ['customer_id', 'status'], unique=False)
    op.create_table('eval_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('email_text', sa.Text(), nullable=False),
    sa.Column('correct_ticket_id', sa.Integer(), nullable=True),
    sa.Column('should_match', sa.Boolean(), nullable=False),
    sa.Column('difficulty_tier', sa.Enum('EASY', 'MODERATE_PARAPHRASE', 'HARD_SEMANTIC', 'HARD_NEGATIVE', 'BOILERPLATE', 'SAME_CUSTOMER_DISAMBIGUATION', name='difficultytier'), nullable=False),
    sa.Column('distractor_ticket_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('tone', sa.Enum('PROFESSIONAL', 'CASUAL', name='tone'), nullable=False),
    sa.Column('length_bucket', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='lengthbucket'), nullable=False),
    sa.Column('noise_level', sa.Enum('CLEAN', 'MILD', 'HEAVY', name='noiselevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['correct_ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_queries_customer_id'), 'eval_queries', ['customer_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('CLIENT', 'ACCOUNT_MANAGER', name='sendertype'), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('intent_type', sa.Enum('INITIAL_REQUEST', 'FOLLOW_UP', 'STATUS_CHECK', 'DOCUMENTATION_PROVIDED', 'THANK_YOU', 'INFORMATIONAL', name='messageintent'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('payer', sa.String(), nullable=True),
    sa.Column('date_of_service', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_ticket_created', 'messages', ['ticket_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_ticket_id'), 'messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_ticket_id'), table_name='messages')
    op.drop_index('ix_messages_ticket_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_eval_queries_customer_id'), table_name='eval_queries')
    op.drop_table('eval_queries')
    op.drop_index('ix_tickets_customer_status', table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_customer_emails_customer_id'), table_name='customer_emails')
    op.drop_table('customer_emails')
    op.drop_table('customers')
    # ### end Alembic commands ###
