"""align schema with production model (inbox_email, drop customer_emails, category/status/message field rework)

Revision ID: da28e3f3a7a1
Revises: 817ec074e0f5
Create Date: 2026-07-27 22:21:23.784166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da28e3f3a7a1'
down_revision: Union[str, Sequence[str], None] = '817ec074e0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_emails_customer_id'), table_name='customer_emails')
    op.drop_table('customer_emails')
    op.add_column('customers', sa.Column('inbox_email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'customers', ['inbox_email'])
    op.drop_column('messages', 'claim_number')
    op.drop_column('messages', 'date_of_service')
    op.drop_column('messages', 'payer')
    op.drop_column('messages', 'intent_type')
    op.drop_column('messages', 'patient_id')
    # ### end Alembic commands ###

    # --- manual: enum member changes (autogenerate does not diff Postgres ENUM
    # members, only column/table presence -- checked, both `tickets` and
    # `messages` are empty on this dev DB, so this is a hard type swap, not a
    # data migration; the old and new category taxonomies don't have a
    # meaningful 1:1 value mapping anyway). ---
    op.drop_index('ix_tickets_customer_status', table_name='tickets')
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'category')
    op.execute('DROP TYPE ticketstatus')
    op.execute('DROP TYPE ticketcategory')
    op.execute('DROP TYPE messageintent')  # orphaned: intent_type column dropped above

    ticket_category = postgresql.ENUM(
        'CLAIMS', 'PAYMENT_POSTING', 'PRIOR_AUTHORIZATION', 'ACCOUNTS_RECEIVABLE',
        'ELIGIBILITY', 'CHARGE_ENTRY', name='ticketcategory',
    )
    ticket_category.create(op.get_bind())
    ticket_status = postgresql.ENUM(
        'OPEN', 'IN_PROGRESS', 'PENDING', 'WAITING_FOR_CLIENT', 'RESOLVED', 'CLOSED',
        name='ticketstatus',
    )
    ticket_status.create(op.get_bind())

    op.add_column('tickets', sa.Column('category', ticket_category, nullable=False))
    op.add_column('tickets', sa.Column('status', ticket_status, nullable=False))
    op.create_index('ix_tickets_customer_status', 'tickets', ['customer_id', 'status'])


def downgrade() -> None:
    """Downgrade schema."""
    # --- manual: revert enum member changes ---
    op.drop_index('ix_tickets_customer_status', table_name='tickets')
    op.drop_column('tickets', 'status')
    op.drop_column('tickets', 'category')
    op.execute('DROP TYPE ticketstatus')
    op.execute('DROP TYPE ticketcategory')

    old_ticket_category = postgresql.ENUM(
        'CLAIM_DENIAL', 'PRIOR_AUTH', 'PAYMENT_POSTING', 'DOCUMENTATION_REQUEST',
        'INSURANCE_VERIFICATION', 'NEW_SERVICE_REQUEST', 'GENERAL_ENQUIRY',
        name='ticketcategory',
    )
    old_ticket_category.create(op.get_bind())
    old_ticket_status = postgresql.ENUM('OPEN', 'CLOSED', name='ticketstatus')
    old_ticket_status.create(op.get_bind())
    old_message_intent = postgresql.ENUM(
        'INITIAL_REQUEST', 'FOLLOW_UP', 'STATUS_CHECK', 'DOCUMENTATION_PROVIDED',
        'THANK_YOU', 'INFORMATIONAL', name='messageintent',
    )
    old_message_intent.create(op.get_bind())

    op.add_column('tickets', sa.Column('category', old_ticket_category, nullable=False))
    op.add_column('tickets', sa.Column('status', old_ticket_status, nullable=False))
    op.create_index('ix_tickets_customer_status', 'tickets', ['customer_id', 'status'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('intent_type', old_message_intent, autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('payer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('date_of_service', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('claim_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'inbox_email')
    op.create_table('customer_emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('customer_emails_customer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_emails_pkey')),
    sa.UniqueConstraint('email_address', name=op.f('customer_emails_email_address_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_customer_emails_customer_id'), 'customer_emails', ['customer_id'], unique=False)
    # ### end Alembic commands ###
